BEGIN;

-- This schema targets PostgreSQL 16 and is intended for a new database.
-- Tables with deleted_at use soft deletion, including association records whose business action can be revoked.

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TABLE roles (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_roles_code UNIQUE (code),
    CONSTRAINT uq_roles_name UNIQUE (name),
    CONSTRAINT chk_roles_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT chk_roles_name_not_blank CHECK (btrim(name) <> '')
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    avatar_url TEXT,
    bio VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_users_username_not_blank CHECK (btrim(username) <> ''),
    CONSTRAINT chk_users_email_format CHECK (
        position('@' IN email) > 1
        AND position('.' IN split_part(email, '@', 2)) > 1
    ),
    CONSTRAINT chk_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT chk_users_display_name_not_blank CHECK (btrim(display_name) <> ''),
    CONSTRAINT chk_users_status CHECK (status IN ('active', 'disabled'))
);

CREATE UNIQUE INDEX uq_users_username_ci ON users (lower(username));
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));

CREATE TABLE user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    role_id SMALLINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_categories_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_categories_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_categories_status CHECK (status IN ('active', 'disabled'))
);

CREATE UNIQUE INDEX uq_categories_parent_name_ci
    ON categories (COALESCE(parent_id, 0), lower(name))
    WHERE deleted_at IS NULL;

CREATE TABLE tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color CHAR(7),
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_tags_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_tags_color CHECK (
        color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'
    )
);

CREATE UNIQUE INDEX uq_tags_name_ci
    ON tags (lower(name))
    WHERE deleted_at IS NULL;

CREATE TABLE knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(500),
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    view_count BIGINT NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_knowledge_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_knowledge_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_knowledge_status CHECK (status IN ('draft', 'published', 'archived')),
    CONSTRAINT chk_knowledge_view_count CHECK (view_count >= 0),
    CONSTRAINT chk_knowledge_published_at CHECK (
        (status = 'published' AND published_at IS NOT NULL)
        OR status <> 'published'
    )
);

CREATE TABLE knowledge_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL REFERENCES knowledge(id) ON DELETE RESTRICT,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    knowledge_id BIGINT NOT NULL REFERENCES knowledge(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    view_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_questions_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_questions_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_questions_status CHECK (status IN ('open', 'resolved', 'closed')),
    CONSTRAINT chk_questions_view_count CHECK (view_count >= 0)
);

CREATE TABLE question_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE RESTRICT,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    content TEXT NOT NULL,
    is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    accepted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_answers_content_not_blank CHECK (btrim(content) <> '')
);

-- Allows at most one active accepted answer for each question.
CREATE UNIQUE INDEX uq_answers_one_accepted_per_question
    ON answers (question_id)
    WHERE is_accepted AND deleted_at IS NULL;

CREATE TABLE answer_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    answer_id BIGINT NOT NULL REFERENCES answers(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_type VARCHAR(20) NOT NULL,
    name VARCHAR(100),
    creator_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    direct_user_low_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    direct_user_high_id BIGINT REFERENCES users(id) ON DELETE RESTRICT,
    last_message_id BIGINT,
    last_message_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_conversations_direct_pair UNIQUE (
        direct_user_low_id,
        direct_user_high_id
    ),
    CONSTRAINT chk_conversations_type CHECK (
        conversation_type IN ('private', 'group')
    ),
    CONSTRAINT chk_conversations_private_pair CHECK (
        (
            conversation_type = 'private'
            AND name IS NULL
            AND direct_user_low_id IS NOT NULL
            AND direct_user_high_id IS NOT NULL
            AND direct_user_low_id < direct_user_high_id
        )
        OR (
            conversation_type = 'group'
            AND btrim(COALESCE(name, '')) <> ''
            AND direct_user_low_id IS NULL
            AND direct_user_high_id IS NULL
        )
    )
);

CREATE TABLE conversation_members (
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    member_role VARCHAR(20) NOT NULL DEFAULT 'member',
    membership_status VARCHAR(20) NOT NULL DEFAULT 'active',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    left_at TIMESTAMPTZ,
    last_read_message_id BIGINT,
    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    is_muted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (conversation_id, user_id),
    CONSTRAINT chk_conversation_members_role CHECK (
        member_role IN ('owner', 'member')
    ),
    CONSTRAINT chk_conversation_members_status CHECK (
        membership_status IN ('active', 'left', 'removed')
    ),
    CONSTRAINT chk_conversation_members_left_at CHECK (
        (membership_status = 'active' AND left_at IS NULL)
        OR (membership_status IN ('left', 'removed') AND left_at IS NOT NULL)
    )
);

CREATE OR REPLACE FUNCTION enforce_private_conversation_member()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    direct_low_id BIGINT;
    direct_high_id BIGINT;
    type_value VARCHAR(20);
BEGIN
    SELECT conversation_type, direct_user_low_id, direct_user_high_id
    INTO type_value, direct_low_id, direct_high_id
    FROM conversations
    WHERE id = NEW.conversation_id;

    IF type_value = 'private'
       AND NEW.user_id NOT IN (direct_low_id, direct_high_id) THEN
        RAISE EXCEPTION
            'private conversation member must belong to its direct user pair';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_conversation_members_private_pair
BEFORE INSERT OR UPDATE OF conversation_id, user_id ON conversation_members
FOR EACH ROW
EXECUTE FUNCTION enforce_private_conversation_member();

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE RESTRICT,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    reply_to_message_id BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    client_message_id VARCHAR(100) NOT NULL,
    message_type VARCHAR(20) NOT NULL DEFAULT 'text',
    content TEXT NOT NULL,
    is_recalled BOOLEAN NOT NULL DEFAULT FALSE,
    recalled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_messages_sender_client_id UNIQUE (
        conversation_id,
        sender_id,
        client_message_id
    ),
    CONSTRAINT chk_messages_client_id_not_blank CHECK (btrim(client_message_id) <> ''),
    CONSTRAINT chk_messages_type CHECK (
        message_type IN ('text', 'image', 'file', 'system')
    ),
    CONSTRAINT chk_messages_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_messages_recalled_at CHECK (
        (is_recalled AND recalled_at IS NOT NULL)
        OR (NOT is_recalled AND recalled_at IS NULL)
    )
);

ALTER TABLE conversations
    ADD CONSTRAINT fk_conversations_last_message
    FOREIGN KEY (last_message_id)
    REFERENCES messages(id)
    ON DELETE SET NULL;

ALTER TABLE conversation_members
    ADD CONSTRAINT fk_conversation_members_last_read_message
    FOREIGN KEY (last_read_message_id)
    REFERENCES messages(id)
    ON DELETE SET NULL;

CREATE OR REPLACE FUNCTION enforce_active_message_sender()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM 1
    FROM conversation_members
    WHERE conversation_id = NEW.conversation_id
      AND user_id = NEW.sender_id
      AND membership_status = 'active';

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'message sender must be an active conversation member';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_messages_active_sender
BEFORE INSERT ON messages
FOR EACH ROW
EXECUTE FUNCTION enforce_active_message_sender();

CREATE OR REPLACE FUNCTION update_conversation_last_message()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE conversations
    SET last_message_id = NEW.id,
        last_message_at = NEW.created_at,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.conversation_id;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_messages_update_conversation_last_message
AFTER INSERT ON messages
FOR EACH ROW
EXECUTE FUNCTION update_conversation_last_message();

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    notification_type VARCHAR(40) NOT NULL,
    resource_type VARCHAR(40) NOT NULL,
    resource_id BIGINT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::JSONB,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT chk_notifications_type CHECK (
        notification_type IN (
            'answer_to_question',
            'answer_liked',
            'knowledge_favorited',
            'answer_accepted',
            'chat_message'
        )
    ),
    CONSTRAINT chk_notifications_resource_type_not_blank CHECK (
        btrim(resource_type) <> ''
    ),
    CONSTRAINT chk_notifications_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT chk_notifications_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT chk_notifications_read_at CHECK (
        (is_read AND read_at IS NOT NULL)
        OR (NOT is_read AND read_at IS NULL)
    )
);

CREATE OR REPLACE FUNCTION set_answer_accepted_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.is_accepted THEN
        IF TG_OP = 'INSERT' THEN
            NEW.accepted_at = CURRENT_TIMESTAMP;
        ELSIF NOT OLD.is_accepted THEN
            NEW.accepted_at = CURRENT_TIMESTAMP;
        END IF;
    ELSE
        NEW.accepted_at = NULL;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_answers_set_accepted_at
BEFORE INSERT OR UPDATE OF is_accepted ON answers
FOR EACH ROW
EXECUTE FUNCTION set_answer_accepted_at();

CREATE TRIGGER trg_roles_updated_at
BEFORE UPDATE ON roles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_user_roles_updated_at
BEFORE UPDATE ON user_roles
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_categories_updated_at
BEFORE UPDATE ON categories
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_tags_updated_at
BEFORE UPDATE ON tags
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_knowledge_tags_updated_at
BEFORE UPDATE ON knowledge_tags
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_favorites_updated_at
BEFORE UPDATE ON favorites
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_knowledge_updated_at
BEFORE UPDATE ON knowledge
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_questions_updated_at
BEFORE UPDATE ON questions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_question_tags_updated_at
BEFORE UPDATE ON question_tags
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_answers_updated_at
BEFORE UPDATE ON answers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_answer_likes_updated_at
BEFORE UPDATE ON answer_likes
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_conversations_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_messages_updated_at
BEFORE UPDATE ON messages
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO roles (code, name, description)
VALUES
    ('user', 'User', 'Default authenticated user role'),
    ('admin', 'Administrator', 'Platform administration role')
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    updated_at = CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX uq_user_roles_active
    ON user_roles (user_id, role_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id, user_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_categories_parent_sort
    ON categories (parent_id, sort_order, id)
    WHERE deleted_at IS NULL AND status = 'active';

CREATE INDEX idx_knowledge_published_category_created
    ON knowledge (category_id, created_at DESC)
    WHERE deleted_at IS NULL AND status = 'published';

CREATE INDEX idx_knowledge_author_updated
    ON knowledge (author_id, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_knowledge_tags_active
    ON knowledge_tags (knowledge_id, tag_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_knowledge_tags_tag_knowledge
    ON knowledge_tags (tag_id, knowledge_id)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_favorites_active
    ON favorites (user_id, knowledge_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_favorites_user_created
    ON favorites (user_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_questions_active_status_created
    ON questions (status, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_questions_author_updated
    ON questions (author_id, updated_at DESC)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_question_tags_active
    ON question_tags (question_id, tag_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_question_tags_tag_question
    ON question_tags (tag_id, question_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_answers_question_created
    ON answers (question_id, created_at ASC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_answers_author_created
    ON answers (author_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX uq_answer_likes_active
    ON answer_likes (user_id, answer_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_answer_likes_answer_id
    ON answer_likes (answer_id)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_conversation_members_user_active
    ON conversation_members (user_id, conversation_id)
    WHERE membership_status = 'active';

CREATE INDEX idx_messages_conversation_created
    ON messages (conversation_id, created_at DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_messages_reply_to ON messages (reply_to_message_id)
    WHERE reply_to_message_id IS NOT NULL;

CREATE INDEX idx_notifications_recipient_created
    ON notifications (recipient_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_notifications_unread
    ON notifications (recipient_id, created_at DESC)
    WHERE deleted_at IS NULL AND NOT is_read;

COMMENT ON TABLE roles IS '角色表，保存平台角色定义，不支持业务删除';
COMMENT ON COLUMN roles.id IS '角色主键';
COMMENT ON COLUMN roles.code IS '角色编码，例如 user 或 admin';
COMMENT ON COLUMN roles.name IS '角色名称';
COMMENT ON COLUMN roles.description IS '角色说明';
COMMENT ON COLUMN roles.created_at IS '创建时间';
COMMENT ON COLUMN roles.updated_at IS '最后更新时间';

COMMENT ON TABLE users IS '用户表，保存账号和个人资料，使用软删除';
COMMENT ON COLUMN users.id IS '用户主键';
COMMENT ON COLUMN users.username IS '登录用户名，大小写不敏感唯一';
COMMENT ON COLUMN users.email IS '邮箱地址，大小写不敏感唯一';
COMMENT ON COLUMN users.password_hash IS '密码安全哈希值，不保存明文密码';
COMMENT ON COLUMN users.display_name IS '用户显示名称';
COMMENT ON COLUMN users.avatar_url IS '用户头像地址';
COMMENT ON COLUMN users.bio IS '个人简介';
COMMENT ON COLUMN users.status IS '账号状态，active 为正常，disabled 为禁用';
COMMENT ON COLUMN users.last_login_at IS '最后登录时间';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.updated_at IS '最后更新时间';
COMMENT ON COLUMN users.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE user_roles IS '用户角色关联表，撤销角色时使用软删除保留历史';
COMMENT ON COLUMN user_roles.id IS '用户角色关联主键';
COMMENT ON COLUMN user_roles.user_id IS '用户主键，关联 users.id';
COMMENT ON COLUMN user_roles.role_id IS '角色主键，关联 roles.id';
COMMENT ON COLUMN user_roles.created_at IS '角色授予时间';
COMMENT ON COLUMN user_roles.updated_at IS '角色关联最后更新时间';
COMMENT ON COLUMN user_roles.deleted_at IS '角色撤销时间，NULL 表示当前有效';

COMMENT ON TABLE categories IS '知识分类表，支持父子分类，使用软删除';
COMMENT ON COLUMN categories.id IS '分类主键';
COMMENT ON COLUMN categories.parent_id IS '父级分类主键，NULL 表示一级分类';
COMMENT ON COLUMN categories.name IS '分类名称，同级有效分类内唯一';
COMMENT ON COLUMN categories.description IS '分类说明';
COMMENT ON COLUMN categories.sort_order IS '排序值，数值越小越靠前';
COMMENT ON COLUMN categories.status IS '分类状态，active 为启用，disabled 为停用';
COMMENT ON COLUMN categories.created_by IS '创建人主键，关联 users.id';
COMMENT ON COLUMN categories.created_at IS '创建时间';
COMMENT ON COLUMN categories.updated_at IS '最后更新时间';
COMMENT ON COLUMN categories.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE tags IS '标签表，供知识和问题复用，使用软删除';
COMMENT ON COLUMN tags.id IS '标签主键';
COMMENT ON COLUMN tags.name IS '标签名称，大小写不敏感唯一';
COMMENT ON COLUMN tags.color IS '标签展示颜色，格式为 #RRGGBB';
COMMENT ON COLUMN tags.created_by IS '创建人主键，关联 users.id';
COMMENT ON COLUMN tags.created_at IS '创建时间';
COMMENT ON COLUMN tags.updated_at IS '最后更新时间';
COMMENT ON COLUMN tags.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE knowledge IS '知识文章表，保存知识库内容，使用软删除';
COMMENT ON COLUMN knowledge.id IS '知识主键';
COMMENT ON COLUMN knowledge.author_id IS '作者主键，关联 users.id';
COMMENT ON COLUMN knowledge.category_id IS '分类主键，关联 categories.id';
COMMENT ON COLUMN knowledge.title IS '知识标题';
COMMENT ON COLUMN knowledge.summary IS '知识摘要';
COMMENT ON COLUMN knowledge.content IS '知识正文';
COMMENT ON COLUMN knowledge.status IS '发布状态，draft 草稿，published 已发布，archived 已归档';
COMMENT ON COLUMN knowledge.view_count IS '浏览次数';
COMMENT ON COLUMN knowledge.published_at IS '发布时间，仅已发布知识必须有值';
COMMENT ON COLUMN knowledge.created_at IS '创建时间';
COMMENT ON COLUMN knowledge.updated_at IS '最后更新时间';
COMMENT ON COLUMN knowledge.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE knowledge_tags IS '知识标签关联表，移除标签时使用软删除保留历史';
COMMENT ON COLUMN knowledge_tags.id IS '知识标签关联主键';
COMMENT ON COLUMN knowledge_tags.knowledge_id IS '知识主键，关联 knowledge.id';
COMMENT ON COLUMN knowledge_tags.tag_id IS '标签主键，关联 tags.id';
COMMENT ON COLUMN knowledge_tags.created_at IS '关联创建时间';
COMMENT ON COLUMN knowledge_tags.updated_at IS '关联最后更新时间';
COMMENT ON COLUMN knowledge_tags.deleted_at IS '关联软删除时间，NULL 表示当前有效';

COMMENT ON TABLE favorites IS '知识收藏表，取消收藏时使用软删除保留历史';
COMMENT ON COLUMN favorites.id IS '收藏记录主键';
COMMENT ON COLUMN favorites.user_id IS '收藏用户主键，关联 users.id';
COMMENT ON COLUMN favorites.knowledge_id IS '被收藏知识主键，关联 knowledge.id';
COMMENT ON COLUMN favorites.created_at IS '收藏时间';
COMMENT ON COLUMN favorites.updated_at IS '收藏记录最后更新时间';
COMMENT ON COLUMN favorites.deleted_at IS '取消收藏时间，NULL 表示当前已收藏';

COMMENT ON TABLE questions IS '问答问题表，保存用户提出的问题，使用软删除';
COMMENT ON COLUMN questions.id IS '问题主键';
COMMENT ON COLUMN questions.author_id IS '提问人主键，关联 users.id';
COMMENT ON COLUMN questions.title IS '问题标题';
COMMENT ON COLUMN questions.content IS '问题正文';
COMMENT ON COLUMN questions.status IS '问题状态，open 待解决，resolved 已解决，closed 已关闭';
COMMENT ON COLUMN questions.view_count IS '浏览次数';
COMMENT ON COLUMN questions.created_at IS '创建时间';
COMMENT ON COLUMN questions.updated_at IS '最后更新时间';
COMMENT ON COLUMN questions.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE question_tags IS '问题标签关联表，移除标签时使用软删除保留历史';
COMMENT ON COLUMN question_tags.id IS '问题标签关联主键';
COMMENT ON COLUMN question_tags.question_id IS '问题主键，关联 questions.id';
COMMENT ON COLUMN question_tags.tag_id IS '标签主键，关联 tags.id';
COMMENT ON COLUMN question_tags.created_at IS '关联创建时间';
COMMENT ON COLUMN question_tags.updated_at IS '关联最后更新时间';
COMMENT ON COLUMN question_tags.deleted_at IS '关联软删除时间，NULL 表示当前有效';

COMMENT ON TABLE answers IS '问题回答表，支持采纳一条回答，使用软删除';
COMMENT ON COLUMN answers.id IS '回答主键';
COMMENT ON COLUMN answers.question_id IS '所属问题主键，关联 questions.id';
COMMENT ON COLUMN answers.author_id IS '回答人主键，关联 users.id';
COMMENT ON COLUMN answers.content IS '回答正文';
COMMENT ON COLUMN answers.is_accepted IS '是否为已采纳回答';
COMMENT ON COLUMN answers.accepted_at IS '被采纳时间，未采纳时为 NULL';
COMMENT ON COLUMN answers.created_at IS '创建时间';
COMMENT ON COLUMN answers.updated_at IS '最后更新时间';
COMMENT ON COLUMN answers.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE answer_likes IS '回答点赞表，取消点赞时使用软删除保留历史';
COMMENT ON COLUMN answer_likes.id IS '点赞记录主键';
COMMENT ON COLUMN answer_likes.user_id IS '点赞用户主键，关联 users.id';
COMMENT ON COLUMN answer_likes.answer_id IS '被点赞回答主键，关联 answers.id';
COMMENT ON COLUMN answer_likes.created_at IS '点赞时间';
COMMENT ON COLUMN answer_likes.updated_at IS '点赞记录最后更新时间';
COMMENT ON COLUMN answer_likes.deleted_at IS '取消点赞时间，NULL 表示当前有效';

COMMENT ON TABLE conversations IS '会话表，支持私聊和群聊，使用软删除';
COMMENT ON COLUMN conversations.id IS '会话主键';
COMMENT ON COLUMN conversations.conversation_type IS '会话类型，private 私聊，group 群聊';
COMMENT ON COLUMN conversations.name IS '群聊名称，私聊为空';
COMMENT ON COLUMN conversations.creator_id IS '会话创建人主键，关联 users.id';
COMMENT ON COLUMN conversations.direct_user_low_id IS '私聊双方中用户主键较小的一方，群聊为空';
COMMENT ON COLUMN conversations.direct_user_high_id IS '私聊双方中用户主键较大的一方，群聊为空';
COMMENT ON COLUMN conversations.last_message_id IS '最后一条消息主键，关联 messages.id';
COMMENT ON COLUMN conversations.last_message_at IS '最后一条消息发送时间';
COMMENT ON COLUMN conversations.created_at IS '创建时间';
COMMENT ON COLUMN conversations.updated_at IS '最后更新时间';
COMMENT ON COLUMN conversations.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE conversation_members IS '会话成员表，退出或移除成员使用状态字段保留历史';
COMMENT ON COLUMN conversation_members.conversation_id IS '会话主键，关联 conversations.id';
COMMENT ON COLUMN conversation_members.user_id IS '成员用户主键，关联 users.id';
COMMENT ON COLUMN conversation_members.member_role IS '会话成员角色，owner 群主，member 普通成员';
COMMENT ON COLUMN conversation_members.membership_status IS '成员状态，active 正常，left 已退出，removed 已移除';
COMMENT ON COLUMN conversation_members.joined_at IS '加入会话时间';
COMMENT ON COLUMN conversation_members.left_at IS '退出或被移除时间，正常成员为空';
COMMENT ON COLUMN conversation_members.last_read_message_id IS '最后已读消息主键，关联 messages.id';
COMMENT ON COLUMN conversation_members.is_pinned IS '是否将会话置顶';
COMMENT ON COLUMN conversation_members.is_muted IS '是否静音该会话';

COMMENT ON TABLE messages IS '聊天消息表，撤回或删除消息时使用软删除';
COMMENT ON COLUMN messages.id IS '消息主键';
COMMENT ON COLUMN messages.conversation_id IS '所属会话主键，关联 conversations.id';
COMMENT ON COLUMN messages.sender_id IS '发送人主键，关联 users.id';
COMMENT ON COLUMN messages.reply_to_message_id IS '被回复消息主键，关联 messages.id';
COMMENT ON COLUMN messages.client_message_id IS '客户端消息唯一标识，用于消息幂等';
COMMENT ON COLUMN messages.message_type IS '消息类型，text 文本，image 图片，file 文件，system 系统消息';
COMMENT ON COLUMN messages.content IS '消息内容或附件信息';
COMMENT ON COLUMN messages.is_recalled IS '是否已撤回';
COMMENT ON COLUMN messages.recalled_at IS '撤回时间，未撤回时为空';
COMMENT ON COLUMN messages.created_at IS '发送时间';
COMMENT ON COLUMN messages.updated_at IS '最后更新时间';
COMMENT ON COLUMN messages.deleted_at IS '软删除时间，NULL 表示未删除';

COMMENT ON TABLE notifications IS '用户通知表，删除通知时使用软删除';
COMMENT ON COLUMN notifications.id IS '通知主键';
COMMENT ON COLUMN notifications.recipient_id IS '通知接收人主键，关联 users.id';
COMMENT ON COLUMN notifications.actor_id IS '触发通知的用户主键，关联 users.id';
COMMENT ON COLUMN notifications.notification_type IS '通知类型，例如回答、点赞、收藏、采纳或聊天消息';
COMMENT ON COLUMN notifications.resource_type IS '关联资源类型';
COMMENT ON COLUMN notifications.resource_id IS '关联资源主键';
COMMENT ON COLUMN notifications.title IS '通知标题';
COMMENT ON COLUMN notifications.content IS '通知正文';
COMMENT ON COLUMN notifications.payload IS '通知扩展数据，JSON 格式';
COMMENT ON COLUMN notifications.is_read IS '是否已读';
COMMENT ON COLUMN notifications.read_at IS '阅读时间，未读时为空';
COMMENT ON COLUMN notifications.created_at IS '创建时间';
COMMENT ON COLUMN notifications.deleted_at IS '软删除时间，NULL 表示未删除';
COMMIT;